### ISSUE TITLE
Breaks With Chrome 48 ...

### ISSUE THREAD

**Issue by brentwcampbell** [michaelphines/NoFavicons#8]
Please fix for Chrome 48!
I just can't stand the favicons.

Thanks in advance,
Brent

**Comment by brentwcampbell** [comment]
Please??

**Comment by michaelphines** [comment]
Chrome 48 opted-in to Apple's new System Integrity Protection feature in El Capitan. By policy, the OS will now deny any scripting additions to be loaded with the app, including SIMBL. The only way to bypass this would be to disable SIP system-wide. I won't provide those instructions here, as I highly recommend against doing this. 

In short, it's unlikely that anyone will be able to make something like this work again without the help and blessing of the Google Chrome team, or forking Chromium itself.

**Comment by brentwcampbell** [comment]
Very sad. Thanks for the update.

Brent

**Comment by w0lfschild** [comment]
I've updated this plugin to work with the latest versions of Chrome. You can get the plugin at https://github.com/w0lfschild/NoFavicons
